# cursor
cursor_shape beam

# cursor blinking
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0

# Smooth cursor
cursor_trail 1
cursor_trail_decay 0.1 0.4

# fonts
font_family      JetBrainsMono Nerd Font
font_size        9.0

# opacitty
background_opacity 1
dynamic_background_opacity yes

# window padding
window_padding_width 15

# remove borders
hide_window_decorations yes

# color theme
include theme.conf
